# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from federation.fed_protobuff import controller_pb2 as federation_dot_fed__protobuff_dot_controller__pb2


class ControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCommunityModelLineage = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/GetCommunityModelLineage',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetCommunityModelLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetCommunityModelLineageResponse.FromString,
        )
    self.GetRuntimeMetadata = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/GetRuntimeMetadata',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetRuntimeMetadataRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetRuntimeMetadataResponse.FromString,
        )
    self.GetServicesHealthStatus = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/GetServicesHealthStatus',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetServicesHealthStatusRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetServicesHealthStatusResponse.FromString,
        )
    self.JoinFederation = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/JoinFederation',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.JoinFederationRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.JoinFederationResponse.FromString,
        )
    self.MarkTaskCompleted = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/MarkTaskCompleted',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.MarkTaskCompletedRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.MarkTaskCompletedResponse.FromString,
        )
    self.LeaveFederation = channel.unary_unary(
        '/federation.fed_protobuff.controller.Controller/LeaveFederation',
        request_serializer=federation_dot_fed__protobuff_dot_controller__pb2.LeaveFederationRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.LeaveFederationResponse.FromString,
        )


class ControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCommunityModelLineage(self, request, context):
    """Unary RPC. Controller replies with community models (0:all, 1:last, 2:previous to last, etc...).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRuntimeMetadata(self, request, context):
    """Unary RPC. Controller replies with federation related runtime metadata (e.g., number of community update requests).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServicesHealthStatus(self, request, context):
    """Unary RPC. Controller replies with the health status (beat) of its internal services.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def JoinFederation(self, request, context):
    """Unary RPC. A new participating learner asks the controller to join the federation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MarkTaskCompleted(self, request, context):
    """Unary RPC. Controller receives the local model of a learner when it completes its local task.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LeaveFederation(self, request, context):
    """Unary RPC. An existing learner informs the controller it leaves the federation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCommunityModelLineage': grpc.unary_unary_rpc_method_handler(
          servicer.GetCommunityModelLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetCommunityModelLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetCommunityModelLineageResponse.SerializeToString,
      ),
      'GetRuntimeMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetRuntimeMetadata,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetRuntimeMetadataRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetRuntimeMetadataResponse.SerializeToString,
      ),
      'GetServicesHealthStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetServicesHealthStatus,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.GetServicesHealthStatusRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.GetServicesHealthStatusResponse.SerializeToString,
      ),
      'JoinFederation': grpc.unary_unary_rpc_method_handler(
          servicer.JoinFederation,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.JoinFederationRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.JoinFederationResponse.SerializeToString,
      ),
      'MarkTaskCompleted': grpc.unary_unary_rpc_method_handler(
          servicer.MarkTaskCompleted,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.MarkTaskCompletedRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.MarkTaskCompletedResponse.SerializeToString,
      ),
      'LeaveFederation': grpc.unary_unary_rpc_method_handler(
          servicer.LeaveFederation,
          request_deserializer=federation_dot_fed__protobuff_dot_controller__pb2.LeaveFederationRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_controller__pb2.LeaveFederationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'federation.fed_protobuff.controller.Controller', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
