# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from federation.fed_protobuff import learner_pb2 as federation_dot_fed__protobuff_dot_learner__pb2


class LearnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunTask = channel.unary_unary(
        '/federation.fed_protobuff.Learner/RunTask',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskResponse.FromString,
        )
    self.LearningMetadataLineage = channel.unary_unary(
        '/federation.fed_protobuff.Learner/LearningMetadataLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LearningMetadataLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LearningMetadataLineageResponse.FromString,
        )
    self.LocalModelLineage = channel.unary_unary(
        '/federation.fed_protobuff.Learner/LocalModelLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LocalModelLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LocalModelLineageResponse.FromString,
        )
    self.EvalModel = channel.unary_unary(
        '/federation.fed_protobuff.Learner/EvalModel',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalModelRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalModelResponse.FromString,
        )
    self.EvalRequestsLineage = channel.unary_unary(
        '/federation.fed_protobuff.Learner/EvalRequestsLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalRequestsLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalRequestsLineageResponse.FromString,
        )
    self.LearnerServicesHeartbeat = channel.unary_unary(
        '/federation.fed_protobuff.Learner/LearnerServicesHeartbeat',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LearnerServicesHeartbeatRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LearnerServicesHeartbeatResponse.FromString,
        )


class LearnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunTask(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LearningMetadataLineage(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LocalModelLineage(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EvalModel(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EvalRequestsLineage(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LearnerServicesHeartbeat(self, request, context):
    """Unary RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunTask': grpc.unary_unary_rpc_method_handler(
          servicer.RunTask,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskResponse.SerializeToString,
      ),
      'LearningMetadataLineage': grpc.unary_unary_rpc_method_handler(
          servicer.LearningMetadataLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LearningMetadataLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LearningMetadataLineageResponse.SerializeToString,
      ),
      'LocalModelLineage': grpc.unary_unary_rpc_method_handler(
          servicer.LocalModelLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LocalModelLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LocalModelLineageResponse.SerializeToString,
      ),
      'EvalModel': grpc.unary_unary_rpc_method_handler(
          servicer.EvalModel,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalModelRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalModelResponse.SerializeToString,
      ),
      'EvalRequestsLineage': grpc.unary_unary_rpc_method_handler(
          servicer.EvalRequestsLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalRequestsLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvalRequestsLineageResponse.SerializeToString,
      ),
      'LearnerServicesHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.LearnerServicesHeartbeat,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.LearnerServicesHeartbeatRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.LearnerServicesHeartbeatResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'federation.fed_protobuff.Learner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
