# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federation/fed_protobuff/optimizers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='federation/fed_protobuff/optimizers.proto',
  package='federation.fed_protobuff.optimizers',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)federation/fed_protobuff/optimizers.proto\x12#federation.fed_protobuff.optimizers\"#\n\nVanillaSGD\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\"=\n\x0bMomentumSGD\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\x12\x17\n\x0fmomentum_factor\x18\x02 \x01(\x02\"7\n\x07\x46\x65\x64Prox\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\x12\x15\n\rproximal_term\x18\x02 \x01(\x02\"N\n\x04\x41\x64\x61m\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\x12\x0e\n\x06\x62\x65ta_1\x18\x02 \x01(\x02\x12\x0e\n\x06\x62\x65ta_2\x18\x03 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x04 \x01(\x02\x62\x06proto3')
)




_VANILLASGD = _descriptor.Descriptor(
  name='VanillaSGD',
  full_name='federation.fed_protobuff.optimizers.VanillaSGD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='federation.fed_protobuff.optimizers.VanillaSGD.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=117,
)


_MOMENTUMSGD = _descriptor.Descriptor(
  name='MomentumSGD',
  full_name='federation.fed_protobuff.optimizers.MomentumSGD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='federation.fed_protobuff.optimizers.MomentumSGD.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='momentum_factor', full_name='federation.fed_protobuff.optimizers.MomentumSGD.momentum_factor', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=180,
)


_FEDPROX = _descriptor.Descriptor(
  name='FedProx',
  full_name='federation.fed_protobuff.optimizers.FedProx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='federation.fed_protobuff.optimizers.FedProx.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proximal_term', full_name='federation.fed_protobuff.optimizers.FedProx.proximal_term', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=237,
)


_ADAM = _descriptor.Descriptor(
  name='Adam',
  full_name='federation.fed_protobuff.optimizers.Adam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='federation.fed_protobuff.optimizers.Adam.learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta_1', full_name='federation.fed_protobuff.optimizers.Adam.beta_1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta_2', full_name='federation.fed_protobuff.optimizers.Adam.beta_2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='federation.fed_protobuff.optimizers.Adam.epsilon', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=317,
)

DESCRIPTOR.message_types_by_name['VanillaSGD'] = _VANILLASGD
DESCRIPTOR.message_types_by_name['MomentumSGD'] = _MOMENTUMSGD
DESCRIPTOR.message_types_by_name['FedProx'] = _FEDPROX
DESCRIPTOR.message_types_by_name['Adam'] = _ADAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VanillaSGD = _reflection.GeneratedProtocolMessageType('VanillaSGD', (_message.Message,), dict(
  DESCRIPTOR = _VANILLASGD,
  __module__ = 'federation.fed_protobuff.optimizers_pb2'
  # @@protoc_insertion_point(class_scope:federation.fed_protobuff.optimizers.VanillaSGD)
  ))
_sym_db.RegisterMessage(VanillaSGD)

MomentumSGD = _reflection.GeneratedProtocolMessageType('MomentumSGD', (_message.Message,), dict(
  DESCRIPTOR = _MOMENTUMSGD,
  __module__ = 'federation.fed_protobuff.optimizers_pb2'
  # @@protoc_insertion_point(class_scope:federation.fed_protobuff.optimizers.MomentumSGD)
  ))
_sym_db.RegisterMessage(MomentumSGD)

FedProx = _reflection.GeneratedProtocolMessageType('FedProx', (_message.Message,), dict(
  DESCRIPTOR = _FEDPROX,
  __module__ = 'federation.fed_protobuff.optimizers_pb2'
  # @@protoc_insertion_point(class_scope:federation.fed_protobuff.optimizers.FedProx)
  ))
_sym_db.RegisterMessage(FedProx)

Adam = _reflection.GeneratedProtocolMessageType('Adam', (_message.Message,), dict(
  DESCRIPTOR = _ADAM,
  __module__ = 'federation.fed_protobuff.optimizers_pb2'
  # @@protoc_insertion_point(class_scope:federation.fed_protobuff.optimizers.Adam)
  ))
_sym_db.RegisterMessage(Adam)


# @@protoc_insertion_point(module_scope)
