//
// Created by Chrysovalantis Anastasiou on 3/10/21.
//

#ifndef PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_CONTROLLER_SERVICE_H_
#define PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_CONTROLLER_SERVICE_H_

class ControllerService {

};

#endif //PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_CONTROLLER_SERVICE_H_
