
#ifndef PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_MODEL_SCALING_MODEL_SCALING_H_
#define PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_MODEL_SCALING_MODEL_SCALING_H_

#include "projectmetis/controller/model_scaling/scaling_function.h"
#include "projectmetis/controller/model_scaling/dataset_size_scaler.h"

#endif //PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_MODEL_SCALING_MODEL_SCALING_H_
