# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from federation.fed_protobuff import learner_pb2 as federation_dot_fed__protobuff_dot_learner__pb2


class LearnerStub(object):
  # missing associated documentation comment in protos file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EvaluateModel = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/EvaluateModel',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvaluateModelRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvaluateModelResponse.FromString,
        )
    self.GetLearningMetadataLineage = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/GetLearningMetadataLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLearningMetadataLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLearningMetadataLineageResponse.FromString,
        )
    self.GetLocalModelLineage = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/GetLocalModelLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLocalModelLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLocalModelLineageResponse.FromString,
        )
    self.GetEvaluationRequestLineage = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/GetEvaluationRequestLineage',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetEvaluationRequestLineageRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetEvaluationRequestLineageResponse.FromString,
        )
    self.GetServicesHealthStatus = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/GetServicesHealthStatus',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetServicesHealthStatusRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetServicesHealthStatusResponse.FromString,
        )
    self.RunTask = channel.unary_unary(
        '/federation.fed_protobuff.learner.Learner/RunTask',
        request_serializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskRequest.SerializeToString,
        response_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskResponse.FromString,
        )


class LearnerServicer(object):
  # missing associated documentation comment in protos file
  pass

  def EvaluateModel(self, request, context):
    """Unary RPC. The learner receives a model and evaluates it at its local dataset (any of [train, validation, test]).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLearningMetadataLineage(self, request, context):
    """Unary RPC. Retrieve recorded metadata in-between community update requests.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLocalModelLineage(self, request, context):
    """Unary RPC. Retrieve most recent and historically trained local models.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEvaluationRequestLineage(self, request, context):
    """Unary RPC. Retrieve all models and metadata related to the models sent for evaluation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServicesHealthStatus(self, request, context):
    """Unary RPC. Retrieve the status of all internal services.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunTask(self, request, context):
    """Unary RPC. Assigned task to be trained locally by the learner.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EvaluateModel': grpc.unary_unary_rpc_method_handler(
          servicer.EvaluateModel,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.EvaluateModelRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.EvaluateModelResponse.SerializeToString,
      ),
      'GetLearningMetadataLineage': grpc.unary_unary_rpc_method_handler(
          servicer.GetLearningMetadataLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLearningMetadataLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLearningMetadataLineageResponse.SerializeToString,
      ),
      'GetLocalModelLineage': grpc.unary_unary_rpc_method_handler(
          servicer.GetLocalModelLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLocalModelLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetLocalModelLineageResponse.SerializeToString,
      ),
      'GetEvaluationRequestLineage': grpc.unary_unary_rpc_method_handler(
          servicer.GetEvaluationRequestLineage,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetEvaluationRequestLineageRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetEvaluationRequestLineageResponse.SerializeToString,
      ),
      'GetServicesHealthStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetServicesHealthStatus,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.GetServicesHealthStatusRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.GetServicesHealthStatusResponse.SerializeToString,
      ),
      'RunTask': grpc.unary_unary_rpc_method_handler(
          servicer.RunTask,
          request_deserializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskRequest.FromString,
          response_serializer=federation_dot_fed__protobuff_dot_learner__pb2.RunTaskResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'federation.fed_protobuff.learner.Learner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
