# EnvironmentConfig:
FederationRounds: 5 # only in synchronous execution
ExecutionCutoffTimeMins: 100000
EvaluationMetric: "accuracy" # Others are "accuracy", "loss
EvaluationMetricCutoffScore: 0.8
CommunicationProtocol: "Synchronous"
ModelStore: "InMemory" # Others are "InMemory", "Redis"
ModelStoreConnectionConfigs:
  Hostname: ""
  Port: 0000
EvictionPolicy: "LineageLengthEviction" # Others are "NoEviction", "LineageLengthEviction"
LineageLength: 1 # This field is only applicable if EvictionPolicy is set to "LineageLengthEviction"

# # homomorphic encryption scheme - if provided run with it, else disabled.
# HEScheme: "CKKS" # Others are "CKKS" (a fully-homomorphic encryption scheme).
# HEBatchSize: 4096
# HEScalingBits: 52

# GlobalTrainingConfig:
AggregationRule: "FedAvg" # Others are FedAvg, FedStride, FedRec, PWA
ScalingFactor: "NumTrainingExamples" # Others are NUM_COMPLETED_BATCHES, NUM_PARTICIPANTS, NUM_TRAINING_EXAMPLES
ParticipationRatio: 1

# LocalTrainingConfig:
BatchSize: 32
LocalEpochs: 4
ValidationPercentage: 0.0
Optimizer: "VanillaSGD" # Others are "MomentumSGD", "Adam", "RMSProp"
OptimizerParams:
  learning_rate: 0.01

# ControllerConfig:
Controller:
  ProjectHome: "/home/panoskyriakis/metisfl"
  ConnectionConfigs:
    Hostname: "localhost"
    Username: "panoskyriakis"
    KeyFilename: "/home/panoskyriakis/.ssh/id_rsa"
    OnLoginCommand: "source /etc/profile;"
  GRPCServicer:
    Hostname: "localhost"
    Port: 50051
  SSLConfigs:
    PrivateKey: "/metisfl/metisfl/resources/ssl_config/default/server-key.pem"
    PublicCertificate: "/metisfl/metisfl/resources/ssl_config/default/server-cert.pem"

# LearnersConfig:
Learners:
  - LearnerID: "localhost-1"
    ProjectHome: "/home/panoskyriakis/metisfl"
    ConnectionConfigs:
      Hostname: "localhost"
      Username: "panoskyriakis"
      KeyFilename: "/home/panoskyriakis/.ssh/id_rsa"
      OnLoginCommand: "source /etc/profile;"
    GRPCServicer:
      Hostname: "localhost"
      Port: 50052
    CudaDevices: [0]
    SSLConfigs:
      PrivateKey: "/metisfl/metisfl/resources/ssl_config/default/server-key.pem"
      PublicCertificate: "/metisfl/metisfl/resources/ssl_config/default/server-cert.pem"