
#ifndef PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_SCHEDULING_SCHEDULING_H_
#define PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_SCHEDULING_SCHEDULING_H_

#include "projectmetis/controller/scheduling/asynchronous_scheduler.h"
#include "projectmetis/controller/scheduling/synchronous_scheduler.h"

#endif //PROJECTMETIS_RC_PROJECTMETIS_CONTROLLER_SCHEDULING_SCHEDULING_H_
