import os 
DEFAULT_LEARNER_HOST = "[::]"
DEFAULT_LEARNER_PORT = 50052
DEFAULT_CONTROLLER_HOSTNAME = "[::]"
DEFAULT_CONTROLLER_PORT = 50051
LEARNER_CREDENTIALS_FP =  "/tmp/metis/learner_{}_credentials/"

LEARNING_TASK = "learning"
EVALUATION_TASK = "evaluation"
INFERENCE_TASK = "inference"
TASKS = [LEARNING_TASK, EVALUATION_TASK, INFERENCE_TASK]

LEARNER_ID_FILE = "learner_id.txt"
AUTH_TOKEN_FILE = "auth_token.txt"

CANCEL_RUNNING_ON_SHUTDOWN = {
    LEARNING_TASK: True,
    EVALUATION_TASK: False,
    INFERENCE_TASK: False
}

if not os.path.exists(LEARNER_CREDENTIALS_FP):
    os.mkdir(LEARNER_CREDENTIALS_FP)

LEARNER_ID_FP = os.path.join(LEARNER_CREDENTIALS_FP, LEARNER_ID_FILE)
AUTH_TOKEN_FP = os.path.join(LEARNER_CREDENTIALS_FP, AUTH_TOKEN_FILE)