"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import metisfl.proto.learner_pb2
import metisfl.proto.model_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Learner(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOSTNAME_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ROOT_CERTIFICATE_BYTES_FIELD_NUMBER: builtins.int
    hostname: builtins.str
    port: builtins.int
    root_certificate_bytes: builtins.str
    def __init__(
        self,
        *,
        hostname: builtins.str = ...,
        port: builtins.int = ...,
        root_certificate_bytes: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hostname", b"hostname", "port", b"port", "root_certificate_bytes", b"root_certificate_bytes"]) -> None: ...

global___Learner = Learner

@typing_extensions.final
class LearnerId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___LearnerId = LearnerId

@typing_extensions.final
class TrainDoneRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def task(self) -> metisfl.proto.learner_pb2.Task: ...
    @property
    def model(self) -> metisfl.proto.model_pb2.Model: ...
    @property
    def results(self) -> global___TrainResults: ...
    def __init__(
        self,
        *,
        task: metisfl.proto.learner_pb2.Task | None = ...,
        model: metisfl.proto.model_pb2.Model | None = ...,
        results: global___TrainResults | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model", b"model", "results", b"results", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model", b"model", "results", b"results", "task", b"task"]) -> None: ...

global___TrainDoneRequest = TrainDoneRequest

@typing_extensions.final
class TrainResults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.float
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    METRICS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    metrics: builtins.str
    """string representation of a JSON object"""
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.float]: ...
    def __init__(
        self,
        *,
        metrics: builtins.str = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "metrics", b"metrics"]) -> None: ...

global___TrainResults = TrainResults

@typing_extensions.final
class Logs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class TrainResultsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___TrainResults: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___TrainResults | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class EvaluationResultsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> metisfl.proto.learner_pb2.EvaluationResults: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: metisfl.proto.learner_pb2.EvaluationResults | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class ModelMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___ModelMetadata: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___ModelMetadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    GLOBAL_ITERATION_FIELD_NUMBER: builtins.int
    TASKS_FIELD_NUMBER: builtins.int
    TRAIN_RESULTS_FIELD_NUMBER: builtins.int
    EVALUATION_RESULTS_FIELD_NUMBER: builtins.int
    MODEL_METADATA_FIELD_NUMBER: builtins.int
    global_iteration: builtins.int
    @property
    def tasks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[metisfl.proto.learner_pb2.Task]: ...
    @property
    def train_results(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___TrainResults]:
        """Indexed by task_id"""
    @property
    def evaluation_results(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, metisfl.proto.learner_pb2.EvaluationResults]: ...
    @property
    def model_metadata(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___ModelMetadata]: ...
    def __init__(
        self,
        *,
        global_iteration: builtins.int | None = ...,
        tasks: collections.abc.Iterable[metisfl.proto.learner_pb2.Task] | None = ...,
        train_results: collections.abc.Mapping[builtins.str, global___TrainResults] | None = ...,
        evaluation_results: collections.abc.Mapping[builtins.str, metisfl.proto.learner_pb2.EvaluationResults] | None = ...,
        model_metadata: collections.abc.Mapping[builtins.str, global___ModelMetadata] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_global_iteration", b"_global_iteration", "global_iteration", b"global_iteration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_global_iteration", b"_global_iteration", "evaluation_results", b"evaluation_results", "global_iteration", b"global_iteration", "model_metadata", b"model_metadata", "tasks", b"tasks", "train_results", b"train_results"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_global_iteration", b"_global_iteration"]) -> typing_extensions.Literal["global_iteration"] | None: ...

global___Logs = Logs

@typing_extensions.final
class ModelMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELECTION_DURATION_MS_FIELD_NUMBER: builtins.int
    AGGREGATION_DURATION_MS_FIELD_NUMBER: builtins.int
    AGGREGATION_BLOCK_SIZE_FIELD_NUMBER: builtins.int
    AGGREGATION_BLOCK_MEMORY_KB_FIELD_NUMBER: builtins.int
    AGGREGATION_BLOCK_DURATION_MS_FIELD_NUMBER: builtins.int
    selection_duration_ms: builtins.float
    aggregation_duration_ms: builtins.float
    @property
    def aggregation_block_size(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def aggregation_block_memory_kb(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def aggregation_block_duration_ms(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        selection_duration_ms: builtins.float = ...,
        aggregation_duration_ms: builtins.float = ...,
        aggregation_block_size: collections.abc.Iterable[builtins.float] | None = ...,
        aggregation_block_memory_kb: collections.abc.Iterable[builtins.float] | None = ...,
        aggregation_block_duration_ms: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["aggregation_block_duration_ms", b"aggregation_block_duration_ms", "aggregation_block_memory_kb", b"aggregation_block_memory_kb", "aggregation_block_size", b"aggregation_block_size", "aggregation_duration_ms", b"aggregation_duration_ms", "selection_duration_ms", b"selection_duration_ms"]) -> None: ...

global___ModelMetadata = ModelMetadata
