# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from metisfl.proto import learner_pb2 as metisfl_dot_proto_dot_learner__pb2
from metisfl.proto import model_pb2 as metisfl_dot_proto_dot_model__pb2
from metisfl.proto import service_common_pb2 as metisfl_dot_proto_dot_service__common__pb2


class LearnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealthStatus = channel.unary_unary(
                '/metisfl.LearnerService/GetHealthStatus',
                request_serializer=metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
                )
        self.GetModel = channel.unary_unary(
                '/metisfl.LearnerService/GetModel',
                request_serializer=metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_model__pb2.Model.FromString,
                )
        self.SetInitialModel = channel.unary_unary(
                '/metisfl.LearnerService/SetInitialModel',
                request_serializer=metisfl_dot_proto_dot_model__pb2.Model.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
                )
        self.Train = channel.unary_unary(
                '/metisfl.LearnerService/Train',
                request_serializer=metisfl_dot_proto_dot_learner__pb2.TrainRequest.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
                )
        self.Evaluate = channel.unary_unary(
                '/metisfl.LearnerService/Evaluate',
                request_serializer=metisfl_dot_proto_dot_learner__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_learner__pb2.EvaluateResponse.FromString,
                )
        self.ShutDown = channel.unary_unary(
                '/metisfl.LearnerService/ShutDown',
                request_serializer=metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
                response_deserializer=metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
                )


class LearnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealthStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInitialModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealthStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthStatus,
                    request_deserializer=metisfl_dot_proto_dot_service__common__pb2.Empty.FromString,
                    response_serializer=metisfl_dot_proto_dot_service__common__pb2.Ack.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=metisfl_dot_proto_dot_service__common__pb2.Empty.FromString,
                    response_serializer=metisfl_dot_proto_dot_model__pb2.Model.SerializeToString,
            ),
            'SetInitialModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInitialModel,
                    request_deserializer=metisfl_dot_proto_dot_model__pb2.Model.FromString,
                    response_serializer=metisfl_dot_proto_dot_service__common__pb2.Ack.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=metisfl_dot_proto_dot_learner__pb2.TrainRequest.FromString,
                    response_serializer=metisfl_dot_proto_dot_service__common__pb2.Ack.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=metisfl_dot_proto_dot_learner__pb2.EvaluateRequest.FromString,
                    response_serializer=metisfl_dot_proto_dot_learner__pb2.EvaluateResponse.SerializeToString,
            ),
            'ShutDown': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutDown,
                    request_deserializer=metisfl_dot_proto_dot_service__common__pb2.Empty.FromString,
                    response_serializer=metisfl_dot_proto_dot_service__common__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metisfl.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealthStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/GetHealthStatus',
            metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
            metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/GetModel',
            metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
            metisfl_dot_proto_dot_model__pb2.Model.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetInitialModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/SetInitialModel',
            metisfl_dot_proto_dot_model__pb2.Model.SerializeToString,
            metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/Train',
            metisfl_dot_proto_dot_learner__pb2.TrainRequest.SerializeToString,
            metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/Evaluate',
            metisfl_dot_proto_dot_learner__pb2.EvaluateRequest.SerializeToString,
            metisfl_dot_proto_dot_learner__pb2.EvaluateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShutDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metisfl.LearnerService/ShutDown',
            metisfl_dot_proto_dot_service__common__pb2.Empty.SerializeToString,
            metisfl_dot_proto_dot_service__common__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
