# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metisfl/proto/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19metisfl/proto/model.proto\x12\x07metisfl\"\xce\x02\n\x05\x44Type\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x13.metisfl.DType.TypeR\x04type\x12\x37\n\nbyte_order\x18\x02 \x01(\x0e\x32\x18.metisfl.DType.ByteOrderR\tbyteOrder\x12#\n\rfortran_order\x18\x03 \x01(\x08R\x0c\x66ortranOrder\"z\n\x04Type\x12\x08\n\x04INT8\x10\x00\x12\t\n\x05INT16\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05INT64\x10\x03\x12\t\n\x05UINT8\x10\x04\x12\n\n\x06UINT16\x10\x05\x12\n\n\x06UINT32\x10\x06\x12\n\n\x06UINT64\x10\x07\x12\x0b\n\x07\x46LOAT32\x10\x08\x12\x0b\n\x07\x46LOAT64\x10\t\"B\n\tByteOrder\x12\x06\n\x02NA\x10\x00\x12\x14\n\x10\x42IG_ENDIAN_ORDER\x10\x01\x12\x17\n\x13LITTLE_ENDIAN_ORDER\x10\x02\"\xbb\x01\n\x10TensorQuantifier\x12-\n\x10tensor_non_zeros\x18\x01 \x01(\rH\x00R\x0etensorNonZeros\x88\x01\x01\x12&\n\x0ctensor_zeros\x18\x02 \x01(\rH\x01R\x0btensorZeros\x88\x01\x01\x12*\n\x11tensor_size_bytes\x18\x03 \x01(\rR\x0ftensorSizeBytesB\x13\n\x11_tensor_non_zerosB\x0f\n\r_tensor_zeros\"\x98\x01\n\x06Tensor\x12\x1c\n\tencrypted\x18\x01 \x01(\x08R\tencrypted\x12\x16\n\x06length\x18\x02 \x01(\rR\x06length\x12\x1e\n\ndimensions\x18\x03 \x03(\x03R\ndimensions\x12\"\n\x04type\x18\x04 \x01(\x0b\x32\x0e.metisfl.DTypeR\x04type\x12\x14\n\x05value\x18\x05 \x01(\x0cR\x05value\"2\n\x05Model\x12)\n\x07tensors\x18\x01 \x03(\x0b\x32\x0f.metisfl.TensorR\x07tensors\"a\n\x0e\x46\x65\x64\x65ratedModel\x12)\n\x10num_contributors\x18\x01 \x01(\rR\x0fnumContributors\x12$\n\x05model\x18\x02 \x01(\x0b\x32\x0e.metisfl.ModelR\x05modelb\x06proto3')



_DTYPE = DESCRIPTOR.message_types_by_name['DType']
_TENSORQUANTIFIER = DESCRIPTOR.message_types_by_name['TensorQuantifier']
_TENSOR = DESCRIPTOR.message_types_by_name['Tensor']
_MODEL = DESCRIPTOR.message_types_by_name['Model']
_FEDERATEDMODEL = DESCRIPTOR.message_types_by_name['FederatedModel']
_DTYPE_TYPE = _DTYPE.enum_types_by_name['Type']
_DTYPE_BYTEORDER = _DTYPE.enum_types_by_name['ByteOrder']
DType = _reflection.GeneratedProtocolMessageType('DType', (_message.Message,), {
  'DESCRIPTOR' : _DTYPE,
  '__module__' : 'metisfl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.DType)
  })
_sym_db.RegisterMessage(DType)

TensorQuantifier = _reflection.GeneratedProtocolMessageType('TensorQuantifier', (_message.Message,), {
  'DESCRIPTOR' : _TENSORQUANTIFIER,
  '__module__' : 'metisfl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.TensorQuantifier)
  })
_sym_db.RegisterMessage(TensorQuantifier)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'metisfl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.Tensor)
  })
_sym_db.RegisterMessage(Tensor)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'metisfl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.Model)
  })
_sym_db.RegisterMessage(Model)

FederatedModel = _reflection.GeneratedProtocolMessageType('FederatedModel', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATEDMODEL,
  '__module__' : 'metisfl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.FederatedModel)
  })
_sym_db.RegisterMessage(FederatedModel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DTYPE._serialized_start=39
  _DTYPE._serialized_end=373
  _DTYPE_TYPE._serialized_start=183
  _DTYPE_TYPE._serialized_end=305
  _DTYPE_BYTEORDER._serialized_start=307
  _DTYPE_BYTEORDER._serialized_end=373
  _TENSORQUANTIFIER._serialized_start=376
  _TENSORQUANTIFIER._serialized_end=563
  _TENSOR._serialized_start=566
  _TENSOR._serialized_end=718
  _MODEL._serialized_start=720
  _MODEL._serialized_end=770
  _FEDERATEDMODEL._serialized_start=772
  _FEDERATEDMODEL._serialized_end=869
# @@protoc_insertion_point(module_scope)
