"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ServingStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServingStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServingStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _ServingStatus.ValueType  # 0
    SERVING: _ServingStatus.ValueType  # 1
    NOT_SERVING: _ServingStatus.ValueType  # 2

class ServingStatus(_ServingStatus, metaclass=_ServingStatusEnumTypeWrapper): ...

UNKNOWN: ServingStatus.ValueType  # 0
SERVING: ServingStatus.ValueType  # 1
NOT_SERVING: ServingStatus.ValueType  # 2
global___ServingStatus = ServingStatus

@typing_extensions.final
class Ack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status: builtins.bool
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    message: builtins.str
    def __init__(
        self,
        *,
        status: builtins.bool = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "status", b"status", "timestamp", b"timestamp"]) -> None: ...

global___Ack = Ack

@typing_extensions.final
class HealthStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___ServingStatus.ValueType
    def __init__(
        self,
        *,
        status: global___ServingStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["status", b"status"]) -> None: ...

global___HealthStatusResponse = HealthStatusResponse

@typing_extensions.final
class GetHealthStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHealthStatusRequest = GetHealthStatusRequest

@typing_extensions.final
class GetHealthStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    @property
    def ack(self) -> global___Ack: ...
    def __init__(
        self,
        *,
        ack: global___Ack | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ack", b"ack"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ack", b"ack"]) -> None: ...

global___GetHealthStatusResponse = GetHealthStatusResponse

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing_extensions.final
class ShutDownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    @property
    def ack(self) -> global___Ack: ...
    def __init__(
        self,
        *,
        ack: global___Ack | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ack", b"ack"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ack", b"ack"]) -> None: ...

global___ShutDownResponse = ShutDownResponse
