load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "controller_proto",
    srcs = ["controller.proto"],
    deps = ["//projectmetis/core/protos:core_proto"],
)
